
name: MadBoy482

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "ULTRA"

          replace: "SuperBot"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          revert_message: 'Replaced new name'

          revert_options: '--no-verify'

          repository: .

          revert_user_name: madboy482

          revert_user_email: madboyop2222@gmail.com
