
name: MadBoy482

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "userbot"

          replace: "SuperBot"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: https://github.com/MadBoy-X/SuperBot/

          commit_user_name: madboy482

          commit_user_email: madboyop2222@gmail.com
